name: replace
description: |-
  Performs a search and replace operation using JS regex expressions (or plain text)
  within files matching a certain glob pattern and returns whether any changes were made.
  Use https://regex101.com/ to test your regex expressions.
  Use https://globster.xyz/ to test your glob patterns.

inputs:
  glob:
    description: |-
      Optional glob pattern to determine which files to perform the search and replace against.
      Defaults to "**/*".
    required: false
    default: "**/*"
  search:
    description: |-
      Regex expression to search for (or set `regex` to "false" to search for plain text instead).
    required: true
  replace:
    description: Text to replace with.
    required: true
  regex:
    description: Whether to enable regex ("true") or not ("false"). Defaults to "true".
    required: false
    default: "true"

outputs:
  changes:
    description: Number of changed files.

runs:
  using: 'node16'
  main: 'dist/index.js'
