name: replace
description: |-
  Performs a search and replace operation using regex expressions (or plain text)
  within files matching a certain glob pattern and returns whether any changes were made.

inputs:
  glob:
    description: |-
      Optional glob pattern to determine which files to perform the search and replace against.
      Defaults to "**/*".
    required: false
    default: "**/*"
  search:
    description: Text to search for.
    required: true
  replace:
    description: Text to replace with.
    required: true
  regex:
    description: Whether to enable regex ("true") or not ("false"). Defaults to "true".
    required: false
    default: "true"

runs:
  using: 'node16'
  main: 'dist/index.js'
